import "~/styles/globals.css";

import { Geist_Mono } from 'next/font/google'
import { type Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { TRPCReactProvider } from "~/trpc/react";

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "MSNS-LMS",
  description: "Generated by MSNS-DEV",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
      <html lang="en">
        <TRPCReactProvider>
                  <SessionProvider >
                  <body className={`${geistMono.variable} antialiased`}>
          {children}
        </body>
        </SessionProvider>
        </TRPCReactProvider>
      </html>
  )
}
