import "~/styles/globals.css";

import { Geist_Mono } from "next/font/google";
import { type Metadata } from "next";
import { Provider } from "~/app/provider";
import { Toaster } from "~/components/ui/sonner";
import { Analytics } from "@vercel/analytics/next"

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MSNS-LMS",
  description: "Generated by MSNS-DEV",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <Analytics />
        <body className={`${geistMono.variable} antialiased`}>
          {children}
          <Toaster />
        </body>
      </Provider>
    </html>
  );
}
