"use client";

import { useSession } from "next-auth/react";
import { api } from "~/trpc/react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "~/components/ui/card";
import { Loader2, DollarSign } from "lucide-react";
import { SalarySlip } from "~/components/tables/SalarySlip";

export function TeacherSalaryTab() {
  const { data: session } = useSession();
  
  const { data: profile, isLoading: isProfileLoading } = api.employee.getProfileByUserId.useQuery(undefined, {
    enabled: !!session?.user,
  });

  const { data: salarySummary, isLoading: isSalaryLoading } = api.salary.getEmployeeSalarySummary.useQuery(
    { employeeId: profile?.employeeId ?? "" },
    { enabled: !!profile?.employeeId }
  );

  if (isProfileLoading || isSalaryLoading) {
    return <div className="flex justify-center p-8"><Loader2 className="h-8 w-8 animate-spin text-emerald-500" /></div>;
  }

  if (!salarySummary || salarySummary.records.length === 0) {
    return (
      <Card className="text-center p-12 bg-white/50 dark:bg-card/50 backdrop-blur-sm border-dashed">
        <DollarSign className="mx-auto h-12 w-12 opacity-20 text-emerald-500" />
        <CardTitle className="mt-4 text-slate-800 dark:text-emerald-100">No Salary Records Found</CardTitle>
        <CardDescription>Your salary slips will appear here once generated by the administration.</CardDescription>
      </Card>
    );
  }

  return (
    <Card className="w-full bg-white/50 dark:bg-card backdrop-blur-xl border-slate-200 dark:border-border shadow-md">
      <CardHeader className="bg-emerald-50/50 dark:bg-emerald-500/5 border-b border-slate-100 dark:border-border">
        <CardTitle className="text-emerald-900 dark:text-emerald-50">Salary Summary</CardTitle>
        <CardDescription className="text-emerald-700/80 dark:text-emerald-100/60">Total Paid: PKR {salarySummary.totalPaid.toLocaleString()}</CardDescription>
      </CardHeader>
      <CardContent className="p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="bg-slate-50 dark:bg-black/20 text-slate-500 dark:text-emerald-100/50">
              <tr>
                <th className="p-4 font-medium uppercase tracking-wider text-xs">Month/Year</th>
                <th className="p-4 font-medium uppercase tracking-wider text-xs">Amount</th>
                <th className="p-4 font-medium uppercase tracking-wider text-xs">Status</th>
                <th className="p-4 font-medium uppercase tracking-wider text-xs text-right">View Slip</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-border">
              {salarySummary.records.map((record) => {
                const totalSalary = record.amount + (record.allowances ?? 0) + (record.bonus ?? 0) - (record.deductions ?? 0);
                const slipData = {
                   id: record.id,
                   employeeId: record.employeeId,
                   baseSalary: record.amount,
                   increment: record.allowances ?? 0,
                   totalSalary: totalSalary,
                   assignedDate: record.paymentDate ?? record.createdAt,
                   sessionId: record.sessionId,
                   Employees: {
                     employeeName: profile?.employeeName ?? "Unknown"
                   },
                   Sessions: {
                     sessionName: "Current Session" 
                   }
                };

                return (
                  <tr key={record.id} className="hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                    <td className="p-4 font-medium text-slate-900 dark:text-foreground">0{record.month}/{record.year}</td>
                    <td className="p-4 text-slate-600 dark:text-emerald-100/80">PKR {totalSalary.toLocaleString()}</td>
                    <td className="p-4">
                      <span className={`px-2.5 py-1 rounded-full text-xs font-semibold ${record.status === "PAID" ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-500/20 dark:text-emerald-300" : "bg-amber-100 text-amber-800 dark:bg-amber-500/20 dark:text-amber-300"}`}>
                        {record.status}
                      </span>
                    </td>
                    <td className="p-4 text-right">
                       {record.status === "PAID" && (
                         /* eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-explicit-any */
                         <SalarySlip salary={slipData as any} />
                       )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  );
}
